services:
  accounts-service:
    image: thepunecoder/accounts:s4
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - thepunecoder-network

  loans-service:
    image: thepunecoder/loans:s4
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - thepunecoder-network

  cards-service:
    image: thepunecoder/cards:s4
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory:
            700M
    networks:
      - thepunecoder-network

networks:
  thepunecoder-network:
    driver: bridge