build:
  version: 3.0.0

accounts:
  message: "Welcome to ThePuneCoder accounts related local APIs"
  contactDetails:
      name: "Devarsh W - Developer"
      email: "devarsh@thepunecoder.com"
  onCallSupport:
      - (555) 555-1234
      - (555) 523-1345