build:
  version: 2.0.0

loans:
  message: "Welcome to ThePuneCoder loans related QA APIs"
  contactDetails:
    name: "Devarsh W - QA Lead"
    email: "qalead@thepunecoder.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345